version: '3.8'

services:

  # .NET Application
  dotnet_contactupdate_app:
    build:
      context: .
      dockerfile: src/Postech.GroupEight.TechChallenge.ContactUpdate.Api/Dockerfile
    container_name: dotnet_contactupdate_app
    restart: always
    ports:
      - "5010:5010"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    networks:
      - techchallenge-worker-persistency_custom_network 

networks:
  techchallenge-worker-persistency_custom_network:
    external: true