global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'dotnet_contactupdate_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['dotnet_contactupdate_app:8081']
        labels:
          app: 'contactupdate_app'
  
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          app: 'rabbitmq'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          app: 'cadvisor'