apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-dotnet-contactupdate
  labels:
    app: techchallenge-dotnet-contactupdate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techchallenge-dotnet-contactupdate
  template:
    metadata:
      labels:
        app: techchallenge-dotnet-contactupdate
    spec:
      containers:
        - name: container-techchallenge-dotnet-contactupdate
          image: lruizd/techchallenge-dotnet-contactupdate:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 5010
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 5010
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          ports:
            - containerPort: 5010
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
---
apiVersion: v1
kind: Service
metadata:
  name: service-techchallenge-dotnet-contactupdate
  labels:
    app: techchallenge-dotnet-contactupdate
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5010
      nodePort: 32000
  selector:
    app: techchallenge-dotnet-contactupdate
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-techchallenge-dotnet-contactupdate
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techchallenge-dotnet-contactupdate
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70