apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-dotnet-contactupdate
  labels:
    app: techchallenge-dotnet-contactupdate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techchallenge-dotnet-contactupdate
  template:
    metadata:
      labels:
        app: techchallenge-dotnet-contactupdate
    spec:
      containers:
        - name: container-techchallenge-dotnet-contactupdate
          image: lruizd/techchallenge-dotnet-contactupdate:v3
          ports:
            - containerPort: 5010
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
---
apiVersion: v1
kind: Service
metadata:
  name: service-techchallenge-dotnet-contactupdate
  labels:
    app: techchallenge-dotnet-contactupdate
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5010
      nodePort: 32000
  selector:
    app: techchallenge-dotnet-contactupdate