apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-dotnet-contactareacode
  labels:
    app: techchallenge-dotnet-contactareacode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge-dotnet-contactareacode
  template:
    metadata:
      labels:
        app: techchallenge-dotnet-contactareacode
    spec:
      containers:
        - name: container-techchallenge-dotnet-contactareacode
          image: lruizd/techchallenge-dotnet-contactareacode:v1
          ports:
            - containerPort: 5012
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
---
apiVersion: v1
kind: Service
metadata:
  name: service-techchallenge-dotnet-contactareacode
  labels:
    app: techchallenge-dotnet-contactareacode
spec:
  type: ClusterIP
  ports:
    - port: 5012
      targetPort: 5012
  selector:
    app: techchallenge-dotnet-contactareacode