apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-dotnet-contactadd
  labels:
    app: techchallenge-dotnet-contactadd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge-dotnet-contactadd
  template:
    metadata:
      labels:
        app: techchallenge-dotnet-contactadd
    spec:
      containers:
        - name: container-techchallenge-dotnet-contactadd
          image: lruizd/techchallenge-dotnet-contactadd:v1
          ports:
            - containerPort: 5011
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
---
apiVersion: v1
kind: Service
metadata:
  name: service-techchallenge-dotnet-contactadd
  labels:
    app: techchallenge-dotnet-contactadd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5011
      nodePort: 31190
  selector:
    app: techchallenge-dotnet-contactadd
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-techchallenge-dotnet-contactadd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techchallenge-dotnet-contactadd
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70