apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  labels:
    app: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
        - name: container-cadvisor
          image: google/cadvisor:latest
          ports:
            - containerPort: 8080
          env:
            - name: CADVISOR_KUBERNETES
              value: "true"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
              readOnly: true
            - mountPath: /host-var-run
              name: varrun
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /var/lib/docker
              name: varlibdocker
              readOnly: true
            - mountPath: /etc/machine-id
              name: machineid
              readOnly: true
            - mountPath: /etc/cadvisor/kubeconfig
              name: kubeconfig
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: varrun
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker
        - name: machineid
          hostPath:
            path: /etc/machine-id
        - name: kubeconfig
          hostPath:
            path: /var/run/secrets/kubernetes.io/serviceaccount
---
apiVersion: v1
kind: Service
metadata:
  name: service-cadvisor
  labels:
    app: cadvisor
spec:
  selector:
    app: cadvisor
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP