apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: techchallenge-dotnet-contactadd
        static_configs:
          - targets: ['service-techchallenge-dotnet-contactadd:80']
      - job_name: techchallenge-dotnet-contactdelete
        static_configs:
          - targets: ['service-techchallenge-dotnet-contactdelete:80']
      - job_name: techchallenge-dotnet-contactfind
        static_configs:
          - targets: ['service-techchallenge-dotnet-contactfind:80']
      - job_name: techchallenge-dotnet-contactupdate
        static_configs:
          - targets: ['service-techchallenge-dotnet-contactupdate:80']
      - job_name: techchallenge-dotnet-contactintegration
        static_configs:
          - targets: ['service-techchallenge-dotnet-contactintegration:5678']
      - job_name: techchallenge-dotnet-contactpersistency
        static_configs:
          - targets: ['service-techchallenge-dotnet-contactpersistency:5679']
      - job_name: postgres-db
        static_configs: 
          - targets: ['service-postgres-db:9187']
      - job_name: mongo-db
        static_configs:
          - targets: ['service-mongo-db:9216']
      - job_name: rabbitmq
        static_configs:
          - targets: ['service-rabbitmq:15692']
      - job_name: cadvisor
        static_configs:
          - targets: ['service-cadvisor:8080']
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    name: prometheus-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  labels:
    name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: container-prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
            - name: prometheus-config
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: service-prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 31196
  selector:
    app: prometheus