apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-dotnet-contactpersistency
  labels:
    app: techchallenge-dotnet-contactpersistency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge-dotnet-contactpersistency
  template:
    metadata:
      labels:
        app: techchallenge-dotnet-contactpersistency
    spec:
      containers:
        - name: container-techchallenge-dotnet-contactpersistency
          image: lruizd/techchallenge-dotnet-contactpersistency:latest
          ports:
            - containerPort: 5679
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: RABBITMQ_HOST
              value: "service-rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: POSTGRES_HOST
              value: "service-postgres-db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "ContactManagementDb"
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: "g3ZcAUKb"
---
apiVersion: v1
kind: Service
metadata:
  name: service-techchallenge-dotnet-contactpersistency
  labels:
    app: techchallenge-dotnet-contactpersistency
spec:
  type: ClusterIP
  ports:
    - port: 5679
      targetPort: 5679
  selector:
    app: techchallenge-dotnet-contactpersistency